### ISSUE TITLE
4/10 Angular 2ハンズオン 東京

### ISSUE THREAD

**Issue by lacolaco** [ng-japan/ng2-hands-on-seed#1]
## アウトライン

教えること
## タイムテーブル

余裕を持って組む
## 備考

4/16 ハンズオン大阪にも流用できるはず

**Comment by lacolaco** [comment]
手を広げるといくら時間があってもたりないので、教えないことを先に決めましょう

**Comment by lacolaco** [comment]
http://kfug.jp/handson/try_angular2/ を参考に項目を分ける
- [x] Hello World(`bootstrap`)
- [x] Interpolation
- [x] Data Binding
- [x] *ngFor
- [x] Event Handling
- [ ] Styling
- [ ] Service & DI
- [ ] Lifecycle Hooks
- [ ] Routing

ちゃんと教えながらやればこれだけでも2,3時間は掛かると思う

**Comment by lacolaco** [comment]
ハンズオンあとの各自やってみようタイムのために、上で触れてないビルトイン機能の紹介も入れたい
- Directives
- Forms
- Input/Output
- Pipes
- `[attr.disabled]`
- `ngClass`
- `ngStyle`
- `*ngIf`
- `ngSwitch`

チートシートの日本語版があるだけでいいのかもしれない。手元においてチートシート見ながら好きなもの作ってもらえればスムーズに行きそう

https://angular.io/docs/ts/latest/guide/cheatsheet.html

実はこれは紙のほうがいいんじゃないかと思ったりする。

**Comment by lacolaco** [comment]
13:40～16:00   ハンズオン
16:00～17:00   オリジナルプロダクト開発-アイディア出し&もくもくタイム
17:00～17:20   オリジナルプロダクト開発-共有会

**Comment by lacolaco** [comment]
13:40〜16:00 140分

13:40〜14:10 30分間でbootstrapと最初の `{{ }}`

**Comment by okunokentaro** [comment]
`npm i`してもらってから今井くんの登壇をすれば、ローディング待ちの間に話が進められる。

**Comment by lacolaco** [comment]
bootstrapの次は 子コンポーネントを作ってネストさせる

**Comment by lacolaco** [comment]
- 子コンポーネントにInputする
- 子コンポーネントからOutputする

**Comment by lacolaco** [comment]
子コンポーネントを`*ngFor`する

**Comment by lacolaco** [comment]
ここまでで 14:30 であってほしい

**Comment by lacolaco** [comment]
次にサービスとDI

**Comment by lacolaco** [comment]
ルーティングまでは大阪と同じ。Stylingの話を省く

**Comment by lacolaco** [comment]
チートシートのシンタックスとビルトイン機能の話を、時間が在ればやる
